// <auto-generated />
namespace Control.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class publish_2704 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(publish_2704));
        
        string IMigrationMetadata.Id
        {
            get { return "201604271948396_publish_2704"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
