// <auto-generated />
namespace Control.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _21062016_puchaseOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_21062016_puchaseOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201605211604152_21062016_puchaseOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
