// <auto-generated />
namespace Control.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_na : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_na));
        
        string IMigrationMetadata.Id
        {
            get { return "201606140116356_update_na"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
