// <auto-generated />
namespace Control.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Pedido_Inclusao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pedido_Inclusao));
        
        string IMigrationMetadata.Id
        {
            get { return "201605102250187_Pedido_Inclusao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
