// <auto-generated />
namespace Control.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CadastroCliente_Add_Endereco_CEP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CadastroCliente_Add_Endereco_CEP));
        
        string IMigrationMetadata.Id
        {
            get { return "201605250015491_CadastroCliente_Add_Endereco_CEP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
